name: Bump Prerelease Version

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  bump-version:
    if: github.repository_owner == 'viamrobotics'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Bump Version
        id: bump_version
        run: |
          poetry version prerelease
          echo "SDK_VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Commit + Push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: 'Bumping prerelease version to v${{ env.SDK_VERSION }}'
